# Generated by Django 4.2.2 on 2023-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
