# Generated by Django 4.2.7 on 2023-12-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='razor_pay_pay_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='razor_pay_pay_sign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
